### ISSUE TITLE
Notary verifying public request fails on sending message/updating github.

### ISSUE THREAD

**Issue by dannyob** [keyko-io/filecoin-verifier-frontend#377]
Clicking on the verify client for https://github.com/filecoin-project/filecoin-plus-client-onboarding/issues/1455 appears to work (I can sign the message on my ledger), but sending the message and updating github fails with the following console log and backtrace.

Eyeballing the error message, it looks like the Message's Value attribute should have the number 0, instead of the string "0".

Thanks for all your work,

d.

```
going to send {"Message":{"From":"f1k6wwevxvp466ybil7y2scqlhtnrz5atjkkyvm4a","GasLimit":9019672,"GasFeeCap":"101535","GasPremium":"100439",
"Method":4,"Nonce":65,"Params":"glUBI+h7fw9m1jHikUReRVpBDk0O3XNHAAoAAAAAAA==",
"To":"f06","Value":"0"},"Signature":{"Data":"EZ0EbtJGu67HTIbQGYWVpYgcp8VnYfvgVTybqY133GR7W3l9pt3rjlwh8Uo5nyu8YmgvtWjhzGY+E9+wCIfcVwE=","Type":1}}

byte-converter.esm.js:118 Uncaught (in promise) Error: "value" paramater isn't a valid number
    at e.value (byte-converter.esm.js:118:35)
    at k (Filters.ts:22:35)
    at DataProvider.tsx:602:37
    at l (runtime.js:63:40)
    at Generator._invoke (runtime.js:294:22)
    at Generator.next (runtime.js:119:21)
    at r (asyncToGenerator.js:3:20)
    at c (asyncToGenerator.js:25:9)
    at asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (asyncToGenerator.js:21:12)
    at Object.updateGithubVerified (DataProvider.tsx:601:33)
    at Notary.tsx:216:34
    at l (runtime.js:63:40)
    at Generator._invoke (runtime.js:294:22)
    at Generator.next (runtime.js:119:21)
    at r (asyncToGenerator.js:3:20)
    at c (asyncToGenerator.js:25:9)
value @ byte-converter.esm.js:118
k @ Filters.ts:22
(anonymous) @ DataProvider.tsx:602
l @ runtime.js:63
(anonymous) @ runtime.js:294
(anonymous) @ runtime.js:119
r @ asyncToGenerator.js:3
c @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
(anonymous) @ DataProvider.tsx:601
(anonymous) @ Notary.tsx:216
l @ runtime.js:63
(anonymous) @ runtime.js:294
(anonymous) @ runtime.js:119
r @ asyncToGenerator.js:3
c @ asyncToGenerator.js:25
```

**Comment by dannyob** [comment]
Sorry, @fabriziogianni7 still hitting the same problem! Happy to test together if you want at some point?

**Comment by dannyob** [comment]
Hey -- so I ran a breakpoint on the error, and it looks like the problem is that there's a call with "10Tib" (for example) for the amount of datacap, rather than the number of bytes *in* 10TiB. Changed it out in the debugger for "10995116277760" and it seemed to clear just fine.

Sorry I don't have a stacktrace, I can try and catch it again when I next see it.

**Comment by fabriziogianni7** [comment]
thanks @dannyob for your support 💯 
It looks like there was a problem with the deploy. can you check again now? 🤞
